/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "calculadora_cientifica.h"
#include <stdio.h>
#include "lex.notacion.h"
#include "stack.h"
#include <stdlib.h>
#include <string.h>

/*nota: dado que no se pueden agregar las cabeceras de los analizadores al mismo
tiempo, se hace uso de archivos para interaccion entre el servidor y las calculadoras.
Tambien para enviar datos a las calculadores se hace el envio mediante otro archivo
y el comando system
*/
float *
calcular_1_svc(entrada *argp, struct svc_req *rqstp)
{
    static float result = 0;
    //declaracion de variables
    FILE *entrada, *res_file, *notacion_file;
    double numero;
    int res_notacion;
    char notacion[2], resultado_final[100];
    printf("se recibe peticion... \n");
    //se guarda cadena recibida por cliente en un archivo
    entrada = fopen("dato_entrada.txt", "w");
    fprintf(entrada, "%s", argp->arg1);
    fclose(entrada);
    //se manda a llamar al ejecutable del analizador de notacion
    //y se envia como entrada la cadena que se guardo en el archivo dato_entrada
    system("./prueba_analiza < dato_entrada.txt");
    //se abre el archivo notacion que es donde se guarda el resultado generado por el analizador
    notacion_file = fopen("notacion.txt", "r");
    //si el archivo existe
    if (notacion_file != NULL)
    {
        //se hace lectura del archivo en el buffer notacion
        fread(notacion, 1, sizeof notacion, notacion_file);
        //se convierte el contenido el buffer en entero
        res_notacion = atoi(notacion);

        //infijo
        if (res_notacion == 1)
        {
            //se manda a llamar a programa de evualuacion infija con cadena ingresada por cliente como 
            system("./prueba_infijo < dato_entrada.txt");
            printf("calculando infijo...\n");
        }
        //postfijo
        else if (res_notacion == 2)
        {
            //se manda a llamar a programa de evualuacion postfija con cadena ingresada por cliente como 
            system("./prueba_postfijo < dato_entrada.txt");
            printf("calculando postfijo...\n");
        }
        //prefijo
        else if (res_notacion == 3)
        {
            //se manda a llamar a programa de evualuacion prefija con cadena ingresada por cliente como 
            system("./prueba_prefijo < dato_entrada.txt");
            printf("calculando prefijo...\n");
        }
        //todas las calculadoras usan el archivo resultado, por lo tanto se abre el archivo 
        //y se convierte contenido en flotante
        res_file = fopen("resultado.txt", "r");
        fread(resultado_final, 1, sizeof resultado_final, res_file);
        numero = atof(resultado_final);
        result = numero;
        fclose(res_file);
    }
    //Se retorna resultado a cliente que solicito operacion
    return &result;
}
