/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "calculadora_cientifica.h"
char lectura[100];

void
calculadoracientifica_1(char *host)
{
	CLIENT *clnt;
	float  *result_1;
	entrada  calcular_1_arg;
	int i = 0;
	while(i <= strlen(lectura)){
	        calcular_1_arg.arg1[i] = lectura[i];
	        i++;
	}	
#ifndef	DEBUG
	clnt = clnt_create (host, CALCULADORACIENTIFICA, CALCULADORACIENTIFICA_VER, "udp");
	if (clnt == NULL) {
		clnt_pcreateerror (host);
		exit (1);
	}
#endif	/* DEBUG */

	result_1 = calcular_1(&calcular_1_arg, clnt);
	if (result_1 == (float *) NULL) {
		clnt_perror (clnt, "call failed");
	}else{
		printf("resultado de operacion: %.2f\n",*result_1);
	}
#ifndef	DEBUG
	clnt_destroy (clnt);
#endif	 /* DEBUG */
}


int
main (int argc, char *argv[])
{
	char *host;

	if (argc < 2) {
		printf ("usage: %s server_host\n", argv[0]);
		exit (1);
	}
	host = argv[1];
	fgets(lectura,100,stdin);
	calculadoracientifica_1 (host);
exit (0);
}
