/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _CALCULADORA_CIENTIFICA_H_RPCGEN
#define _CALCULADORA_CIENTIFICA_H_RPCGEN

#include <rpc/rpc.h>


#ifdef __cplusplus
extern "C" {
#endif


struct entrada {
	char arg1[100];
};
typedef struct entrada entrada;

#define CALCULADORACIENTIFICA 0x30000001
#define CALCULADORACIENTIFICA_VER 1

#if defined(__STDC__) || defined(__cplusplus)
#define calcular 1
extern  float * calcular_1(entrada *, CLIENT *);
extern  float * calcular_1_svc(entrada *, struct svc_req *);
extern int calculadoracientifica_1_freeresult (SVCXPRT *, xdrproc_t, caddr_t);

#else /* K&R C */
#define calcular 1
extern  float * calcular_1();
extern  float * calcular_1_svc();
extern int calculadoracientifica_1_freeresult ();
#endif /* K&R C */

/* the xdr functions */

#if defined(__STDC__) || defined(__cplusplus)
extern  bool_t xdr_entrada (XDR *, entrada*);

#else /* K&R C */
extern bool_t xdr_entrada ();

#endif /* K&R C */

#ifdef __cplusplus
}
#endif

#endif /* !_CALCULADORA_CIENTIFICA_H_RPCGEN */
